# -*- coding: utf-8 -*-
"""Basic Matplotlib Work

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wtmSzxaPh1QFurPwF2PfM4gfq2iD_MZJ
"""

# Line Graph
from matplotlib import pyplot as plt
plt.plot([1,2,3],[4,5,1])
plt.title('Info')
plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.show()



# Adding Style to line graph
from matplotlib import pyplot as plt
from matplotlib import style 
style.use('ggplot')
x=[5,8,10]
y=[12,6,6]

x2=[6,9,11]
y2=[6,15,7]

plt.plot(x,y,'green', label='line one', linewidth = 5)
plt.plot(x2,y2,'blue', label='line two', linewidth = 5)
plt.title('Epic Info')
plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.legend()
plt.grid(True, color = 'black')
plt.show()

# Bar Graph
import matplotlib.pyplot as plt
plt.bar([1,3,5,7,9],[5,2,7,8,2], label = 'Example one' , color = 'pink')
plt.bar([2,4,6,8,10],[8,6,2,5,6], label = 'Example two' , color = 'c')
plt.legend()
plt.xlabel('Bar Number')
plt.ylabel('Bar Height')
plt.title('Info0')
plt.show()

# Histogram
import matplotlib.pyplot as plt
population_ages = [22,55,62,45,25,22,34,42,42,4,99,102,110,120,121,122]
bins = [0,10,20,30,40,50,60,70,80,90,100,110,120,130]
plt.hist(population_ages,bins, histtype = 'bar', rwidth = .8 , color = 'c')
plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.title('Histogram')
plt.show()

#scatter Graph
import matplotlib.pyplot as plot
x=[1,2,3,4,5,6,7,8]
y = [5,2,4,2,1,4,5,2]
plt.scatter(x,y, label = 'skitscat', color = 'k')
plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.legend()
plt.show()

# stack plot
import matplotlib.pyplot as plt
days = [1,2,3,4,5]
sleeping = [7,8,6,11,7]
eating = [2,3,4,3,2]
working = [7,8,7,2,2]
playing = [8,5,7,8,13]
plt.plot([],[], color = 'pink' , label = 'sleeping' , linewidth = 5)
plt.plot([],[], color = 'c' , label = 'eating' , linewidth = 5)
plt.plot([],[], color = 'r' , label = 'working' , linewidth = 5)
plt.plot([],[], color = 'g' , label = 'playing' , linewidth = 5)
plt.stackplot(days, sleeping , eating , working , playing , colors = ['pink','c','r','g'])
plt.xlabel(' X Axis')
plt.ylabel(' Y Axis')
plt.legend()
plt.title('stack Plot')
plt.show()

# pie Chart
slices = [ 7,2,2,13]
activities = ['Sleeping', 'Eating', 'Working' , 'Playing']
cols= ['brown', 'yellow' , 'c', 'pink']
plt.pie (slices , labels = activities , colors= cols , startangle = 90 , shadow = True , explode = (0,0.1,0,0), autopct = '%1.1f%%')
plt.title('Pie pLot')
plt.show()